-- Fix activity logs table to use VARCHAR instead of UUID for NextAuth compatibility
-- This fixes the error: invalid input syntax for type uuid: "cmixd9krk0000yfoq4suc5l5g"

-- Step 1: Drop foreign key constraint on workspace_id
ALTER TABLE public.autopostvn_system_activity_logs 
DROP CONSTRAINT IF EXISTS autopostvn_system_activity_logs_workspace_id_fkey;

-- Step 2: Alter user_id column from UUID to VARCHAR
ALTER TABLE public.autopostvn_system_activity_logs 
ALTER COLUMN user_id TYPE VARCHAR(255) USING user_id::VARCHAR;

-- Step 3: Alter workspace_id column from UUID to VARCHAR (can be NULL)
ALTER TABLE public.autopostvn_system_activity_logs 
ALTER COLUMN workspace_id TYPE VARCHAR(255) USING workspace_id::VARCHAR;

-- Step 4: Alter target_resource_id column from UUID to VARCHAR (can be NULL)
ALTER TABLE public.autopostvn_system_activity_logs 
ALTER COLUMN target_resource_id TYPE VARCHAR(255) USING target_resource_id::VARCHAR;

-- Note: The id column remains as UUID since it's auto-generated by PostgreSQL
-- Note: Foreign key constraint on workspace_id removed because workspaces table uses UUID
--       while NextAuth users use CUID strings. Will need to handle referential integrity at application level.
